runtime: nodejs12
# env: flex
resources:
    cpu: 2
    memory_gb: 4.0
    disk_size_gb: 20
env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/sparkcourse:us-west2:my-sql-sparkcourse;dbname=spark_course_db
  MYSQL_USER: root
  MYSQL_PASSWORD: 'Bluestone101!'
handlers:
    - url: /
      static_files: public/login.html
      upload: public/login.html
    - url: /
      static_files: public/css/login.css
      upload: public/css/login.css
    - url: /
      static_files: public/js/login.js
      upload: public/js/login.js
#   - url: /
#     static_files: /login.html
#     upload: public/login.html
#   - url: /(.*)
#     static_files: www/\1
#     upload: www/(.*)
beta_settings:
  cloud_sql_instances: sparkcourse:us-west2:my-sql-sparkcourse

  
# https://sparkcourse.appspot.com/login.html